### ISSUE TITLE
Nested objects don't work in useForm post request.

### ISSUE THREAD

**Issue by illogikal** [formidablejs/framework#121]
```
useForm({
  test: [{a:'a'}]
})
useForm({
  test: ''
})
```

The first does not post, the second one works successfully.

**Comment by donaldp** [comment]
Closing this issue, updates to follow in the [@formidablejs/view](https://github.com/formidablejs/framework) repository.

Updates: [https://github.com/formidablejs/view/issues/9](https://github.com/formidablejs/view/issues/9)
