### ISSUE TITLE
Error shown in the console

### ISSUE THREAD

**Issue by haikyuu** [formidablejs/framework#140]
I see these errors in the console on a fresh install. I don't even have any sessions nor custom code
```
ℹ listening on http://::1:3000/
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'storage/sessions/0mI12SRd0Uu5UM1fji599zWTtLFjQGn5.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'storage/sessions/0mI12SRd0Uu5UM1fji599zWTtLFjQGn5.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'storage/sessions/0mI12SRd0Uu5UM1fji599zWTtLFjQGn5.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'storage/sessions/0mI12SRd0Uu5UM1fji599zWTtLFjQGn5.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'storage/sessions/0mI12SRd0Uu5UM1fji599zWTtLFjQGn5.json'
```

Is it linked to this `[session-file-store] Deleting expired sessions`?

How to reproduce:
- Create a new project and keep it running for a day. (many `[session-file-store] Deleting expired sessions` in the logs)
- restart and you will see these errors

**Comment by donaldp** [comment]
Hi @haikyuu 

Thanks for reporting the issue, currently investigating 👍

**Comment by haikyuu** [comment]
I didn't reproduce it afterwards. I think it happened because I was using express session middleware in a previous project that was on the same host localhost:3000
